version: '2'

services:

    app:
        build: app
        volumes:
            - ../..:/usr/src/app
        privileged: true

    mpd_server:
        build: mpd_server
        volumes:
            - /media/MUSIC:/media/MEDIA
        ports:
            - "6600:6600"
        privileged: true
