version: '2'

services:

    app:
        build: app
        volumes:
            - ../..:/usr/src/app

    mpd_server:
        build: mpd_server
        volumes:
            - /media/MUSIC:/media/MEDIA
